### ISSUE TITLE
Database incorporated into another project

### ISSUE THREAD

**Issue by supertorpe** [calebjcourtney/chess-endgame-training#5]
Hi, I've added 10.000 positions from your database to my Chess Endgame Training project (https://github.com/supertorpe/chessendgametraining    /   https://chess-endgame-trainer.mooo.com/), under the menu "Checkmate in...".

So you can play them now with a frontend, along with thousands of other categorized positions that the application already included.

**Comment by calebjcourtney** [comment]
Hey, that frontend looks amazing! Thanks for letting me know. I'm glad it was helpful to someone else.
