### ISSUE TITLE
Database needs review

### ISSUE THREAD

**Issue by supertorpe** [calebjcourtney/chess-endgame-training#6]
There are positions in the database that do not correspond to checkmate in the number of movements registered. To give a small sample, these 4 are registered as moves=1 but they do not represent checkmate in 1 move:

r3r2k/bpp2p2/p1n2n1p/P3N1N1/1P6/1qPP2BP/5PP1/R4RK1 w - - 1 20
r3k1r1/p1pqb1pp/1p1p1p2/1P2p3/3nP3/N1PP4/P3QPPP/R1B2RK1 w q - 0 14
r3kbnr/3q1pp1/p1np3p/1pp5/1PP1P3/1B1PB3/P4QPP/RN3RK1 w kq - 1 15
1n5r/rp3ppp/p1k1p3/1N6/PP6/2P5/5PPP/R4RK1 w - - 1 17

**Comment by calebjcourtney** [comment]
Thanks for pointing this out. Yeah, this was pulled from the Lichess database. I pulled the analysis from the pgn file, but it looks like that analysis from Lichess is incorrect. I'll go through and validate the positions against stockfish and update the database to ensure everything is correct.

**Comment by calebjcourtney** [comment]
@supertorpe Updated the database after a thorough check of each FEN against the stockfish engine. 

Currently, there are fewer than the 100k positions (10 for each depth), which I am working on resolving, but I wanted to at least get rid of the garbage positions where there was no mate.

**Comment by supertorpe** [comment]
Great! Thank you for your work! It's CPU consuming to verify all those positions.

**Comment by calebjcourtney** [comment]
@supertorpe, wanted to ping you on this. The current sqlite database should be up-to-date, though please let me know if you have any issues. I'll leave this issue open through the end of the week, in case you run into any related problems.

**Comment by supertorpe** [comment]
I'll be away, unable to do tests or checks until next month. Anyway I only needed to take a subset of 10.000 curated positions.
As for me, you can close the issue.
Thanks!
